<a href="https://colab.research.google.com/github/deenaseban/Heart_Disease_Prediction/blob/main/ml_knn3_heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/heart_missing (1).csv')
df

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1      53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2      70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3      61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4      62    0  0.0       138   294  1.0      1.0      106      0      1.9   
...   ...  ...  ...       ...   ...  ...      ...      ...    ...      ...   
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df.head()

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1   53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2   70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3   61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4   62    0  0.0       138   294  1.0      1.0      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

In [ ]:
df.tail()

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
df.isna().sum()

age          0
sex          0
cp           7
trestbps     0
chol         0
fbs         13
restecg      4
thalach      0
exang        0
oldpeak     11
slope        0
ca           0
thal         0
target       0
dtype: int64

In [ ]:
a=df['cp'].mean()
df['cp'].fillna(a,inplace=True)
b=df['fbs'].mean()
df['fbs'].fillna(b,inplace=True)
c=df['restecg'].mean()
df['restecg'].fillna(c,inplace=True)
d=df['oldpeak'].mean()
df['oldpeak'].fillna(d,inplace=True)
df

age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1  0.0       125   212  0.0      1.0      168      0      1.0   
1      53    1  0.0       140   203  1.0      0.0      155      1      3.1   
2      70    1  0.0       145   174  0.0      1.0      125      1      2.6   
3      61    1  0.0       148   203  0.0      1.0      161      0      0.0   
4      62    0  0.0       138   294  1.0      1.0      106      0      1.9   
...   ...  ...  ...       ...   ...  ...      ...      ...    ...      ...   
1020   59    1  1.0       140   221  0.0      1.0      164      1      0.0   
1021   60    1  0.0       125   258  0.0      0.0      141      1      2.8   
1022   47    1  0.0       110   275  0.0      0.0      118      1      1.0   
1023   50    0  0.0       110   254  0.0      0.0      159      0      0.0   
1024   54    1  0.0       120   188  0.0      1.0      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
# Training and Testing Data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,

In [ ]:
# Normalization
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)


In [ ]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)


In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
mtrx=confusion_matrix(y_test,y_pred)
print(mtrx)


[[127  32]
 [ 16 133]]


In [ ]:
# Accuracy score
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.8441558441558441